# Generated by Django 6.0.2 on 2026-02-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_assigned_delivery_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('delivery', 'Delivery Boy'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
